[package]
name = "scepa"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.92"
bon = "3.9.3"
chrono = { version = "0.4.42", features = ["serde"] }
eros = "0.7.0"
hex = "0.4.3"
hmac = "0.12.1"
nonempty-collections = "1.4.0"
qdrant-client = "1.19.0"
quick-xml = "0.38.3"
reqwest = { version = "0.13.4", features = ["json", "multipart"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
sha2 = "0.10.9"
sqlx = { version = "0.9.0", default-features = false, features = ["json", "macros", "migrate", "postgres", "runtime-tokio"] }
tokio = { version = "1.53.1", features = ["fs"] }
tracing = "0.1.41"
typedb-driver = "3.12.3"

[dev-dependencies]
tokio = { version = "1.53.1", features = ["fs", "macros", "rt-multi-thread"] }
